### ISSUE TITLE
うまく動かないmidiがある

### ISSUE THREAD

**Issue by ch4rindo** [maa123/MIDI2PMMP#2]

**Comment by ch4rindo** [comment]
説明文書き忘れてしまい申し訳ありません。
左手(?)と右手パートの曲の速さが一致しないmidiがあります
おそらくConverterの問題でしょうか...

**Comment by maa123** [comment]
手元のファイルでは確認できていません。
MIDIファイルがFormat1の物であればFormat0で保存してから試していただけないでしょうか？

**Comment by ch4rindo** [comment]
Format0で試したところ正常に動作しました。
お手数をおかけして申し訳ありませんでした。
